// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package client

import "encoding/json"
import "fmt"

type Footer struct {
	// Signature created based on the binary data. Contains an incremental SHA256 hash
	// of the given hash list and the file size. Signed by an ApiKey of the Account
	ClientSignature string `json:"clientSignature" yaml:"clientSignature" mapstructure:"clientSignature"`

	// Size of the binary in bytes
	FileSize int `json:"fileSize" yaml:"fileSize" mapstructure:"fileSize"`

	// Individual hashes of slices of the binary data. Each hash is a tuple of the
	// SHA256 hash and the amount of bytes that were hashed
	Hashes []HashTuple `json:"hashes" yaml:"hashes" mapstructure:"hashes"`

	// Base64 encoded signature of the `clientSignature` field. Signed by one of the
	// ApiKeys of the StorageProvider
	StorageProviderSignature string `json:"storageProviderSignature" yaml:"storageProviderSignature" mapstructure:"storageProviderSignature"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Footer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["clientSignature"]; raw != nil && !ok {
		return fmt.Errorf("field clientSignature in Footer: required")
	}
	if _, ok := raw["fileSize"]; raw != nil && !ok {
		return fmt.Errorf("field fileSize in Footer: required")
	}
	if _, ok := raw["hashes"]; raw != nil && !ok {
		return fmt.Errorf("field hashes in Footer: required")
	}
	if _, ok := raw["storageProviderSignature"]; raw != nil && !ok {
		return fmt.Errorf("field storageProviderSignature in Footer: required")
	}
	type Plain Footer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Footer(plain)
	return nil
}

type HashTuple []string

// HTTP headers as key-value pairs
type Headers map[string]string

type Request struct {
	// Request body as base64-encoded bytes
	Body *string `json:"body,omitempty" yaml:"body,omitempty" mapstructure:"body,omitempty"`

	// Headers corresponds to the JSON schema field "headers".
	Headers Headers `json:"headers" yaml:"headers" mapstructure:"headers"`

	// HTTP method (GET, POST, PUT, DELETE, etc.)
	Method string `json:"method" yaml:"method" mapstructure:"method"`

	// Request URL
	Url string `json:"url" yaml:"url" mapstructure:"url"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Request) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["headers"]; raw != nil && !ok {
		return fmt.Errorf("field headers in Request: required")
	}
	if _, ok := raw["method"]; raw != nil && !ok {
		return fmt.Errorf("field method in Request: required")
	}
	if _, ok := raw["url"]; raw != nil && !ok {
		return fmt.Errorf("field url in Request: required")
	}
	type Plain Request
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Request(plain)
	return nil
}

type Response struct {
	// Response body as plain text, or base64-encoded bytes
	Body *string `json:"body,omitempty" yaml:"body,omitempty" mapstructure:"body,omitempty"`

	// Headers corresponds to the JSON schema field "headers".
	Headers Headers `json:"headers,omitempty" yaml:"headers,omitempty" mapstructure:"headers,omitempty"`
}

type StorageProviderPayload struct {
	// Array of version strings for PUT requests
	Versions []string `json:"versions,omitempty" yaml:"versions,omitempty" mapstructure:"versions,omitempty"`
}

// Schema for StoreEventRequest with nested Request and Footer objects
type StoreEventRequestJson struct {
	// Additional meta data about the uploaded binary.
	Footer *Footer `json:"footer,omitempty" yaml:"footer,omitempty" mapstructure:"footer,omitempty"`

	// Request that was sent by the SDK to the MinIO Extension
	Request Request `json:"request" yaml:"request" mapstructure:"request"`

	// Response that MinIO itself returns to the MinIO Extension
	Response Response `json:"response" yaml:"response" mapstructure:"response"`

	// Additional fields that are additionally added by the MinIO Extension, which are
	// not part of the default response of MinIO
	StorageProviderPayload string `json:"storageProviderPayload" yaml:"storageProviderPayload" mapstructure:"storageProviderPayload"`

	// Base64 encoded signature of the `x-lmwrntwrk-signature` field. Signed by one of
	// the ApiKeys of the StorageProvider
	StorageProviderS3Signature string `json:"storageProviderS3Signature" yaml:"storageProviderS3Signature" mapstructure:"storageProviderS3Signature"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StoreEventRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["request"]; raw != nil && !ok {
		return fmt.Errorf("field request in StoreEventRequestJson: required")
	}
	if _, ok := raw["response"]; raw != nil && !ok {
		return fmt.Errorf("field response in StoreEventRequestJson: required")
	}
	if _, ok := raw["storageProviderPayload"]; raw != nil && !ok {
		return fmt.Errorf("field storageProviderPayload in StoreEventRequestJson: required")
	}
	if _, ok := raw["storageProviderS3Signature"]; raw != nil && !ok {
		return fmt.Errorf("field storageProviderS3Signature in StoreEventRequestJson: required")
	}
	type Plain StoreEventRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = StoreEventRequestJson(plain)
	return nil
}
